#!/usr/bin/env python3
import matplotlib.pyplot as plt
x = range(5)
y1 = x
y2 = [4, 3, 2, 1, 0]
bound_below = [0] * 5
bound_above = [4] * 5

plt.scatter(x, y1, label='strictly increasing, monotonic, bounded')
plt.scatter(x, y2, label='strictly decreasing, monotonic, bounded')
plt.plot(x, bound_below, label='lower bound')
plt.plot(x, bound_above, label='upper bound')
plt.title('5.5.12')
plt.xlabel('N')
plt.ylabel('A totally ordered set, A')
plt.legend()
plt.show()

